- hosts: terraform-ansible
  tasks:
    - name: Install python3 and virtualenv
      become: yes
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes

    - name: Install pip dependencies
      pip:
        virtualenv: /home/ubuntu/app/venv
        name:
          - django
          - djangorestframework

    - name: Create django project
      shell: '. /home/ubuntu/app/venv/bin/activate; django-admin startproject setup /home/ubuntu/app'

    - name: Configure django ALLOWED_HOSTS
      lineinfile:
        path: /home/ubuntu/app/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
