- hosts: terraform-ansible
  tasks:
    - name: Create index.html file
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>First EC2 with Terraform + Ansible</h1>

    - name: Create HTTP server
      shell: "nohup busybox httpd -f -p 8080 &"
